### ISSUE TITLE
Redefine the spec for .hal.yml configuration

### ISSUE THREAD

**Issue by skluck** [hal-platform/hal#34]
Need to update the schema for this file to match terms from #9

Also the file should be changed to `.hal.yml`

**Comment by skluck** [comment]
Example:
```yaml
system: "docker/image:tag"

build:
    system: "docker:image"
    env:
        MY_SAMPLE_VAR: "value"
        MY_SAMPLE_VAR: "value"
    dist: './relative/build_output_dir'
    commands:
        - "chmod +x some/randomfile.sh"
        - "./build_command.sh"

build_transform:
    system: "docker:image"
    dist: './relative/build_output_dir'
    commands:
        - "rm -rf unneeded_files/*"
        - ["custom-docker/image", "command"]

deploy:

    rsync:
        exclude:
            - "excluded_dir"
            - "config/*.txt"
        before:
            - "command.sh"
            - ["file", "command"]
        after:
            - "command.sh"

    script:
        system: "custom/docker-image"
        commands:
            -  "ssh user@server run_command.sh"
            -  "./script_command.sh"
```

Changes

- `exclude` moved under `deploy.rsync`
- `pre_push` changed to `deploy.rsync.before`
- `post_push` changed to `deploy.rsync.after`
- added `["file", "command"]` format to `deploy.rsync.(commands)` to force syncing of file before execution
- `deploy` changed to `deploy.script.commands`
- added `system` to build, build_transform, and `deploy.script` so users can specify global setting, and for individual steps.
- moved `dist` to `build.dist`
- added `build_transform.dist`
- changed `docker:custom/image command.sh` format to `["custom/image", "command.sh"]`
- added `env` to build, build_transform, and `deploy.script`

**Comment by skluck** [comment]
- Change `build_transform` to `release` stage.
- Support `before` and `after` for every stage.
- Support global config
- Module-specific config under `config` section
- System now requires extra config to explicitly define type (docker, etc)

```yaml
# global config for all stages

config:
    system:
        type: "docker"
        image: "repo/image:tag"
    env:
        MY_SAMPLE_VAR4: "value5"

# stage (build)

build: # no environment given
    config:
        system:
            type: "docker"
            image: "image:tag"
        env:
            MY_SAMPLE_VAR: "value"
            MY_SAMPLE_VAR2: "value"
        output: './relative/build_output_dir'

    before:
        - "command1"

    run:
        - "chmod +x some/randomfile.sh"
        - "./build_command.sh"

    after:
        - "command1"

# stage (release)

release: # formerly: build_transform, has environment
    config:
        system:
            type: "docker"
            image: "buildpack/image:version"
        env:
            MY_SAMPLE_VAR: "value"
        output: './relative_dir'

    run:
        - "rm -rf unneeded_files/*"

# stage (deploy)

deploy:

    rsync:
        config:
            input: "./relative_dir"
            exclude:
                - "excluded_dir"
                - "config/*.txt"
            on_server:
                before_push:
                    - "./stop_server.sh"
                after_push:
                    - "./start_server.sh"

        before:
            - "command.sh"
        after:
            - "if [ $STAGE_STATUS == "SUCCESS" ]; then ./command.sh; fi"
            - "if [ $STAGE_STATUS == "FAILURE" ]; then ./notify.sh; fi"

    script:
        config:
            system:
                type: "docker"
                image: "custom/image:version"

        before: []

        run:
            -  "ssh user@server run_command.sh"
            -  "./script_command.sh"

        after: []
```
